### ISSUE TITLE
Code Detail

### ISSUE THREAD

**Issue by hemangmehta** [alexa/skill-sample-nodejs-hello-world#1]
Hi, It's good too see alexa-sdk live finally. thanks for writing a sample code. 
Can you please explain this code bit, or how to execute/run this sample code ? Actually my main concern is how to use existing alexa skill (which i have created in developer console) here.

Can you please help me out.
Thanks

**Comment by deegles** [comment]
Hi hemangmehta, 

We are working on updated tutorials for each of the sample skills, stay tuned!

For now, you can follow the instructions in the following blog post and adapt it to use the sample you wish.

https://developer.amazon.com/public/community/post/Tx3DVGG0K0TPUGQ/New-Alexa-Skills-Kit-Template:-Step-by-Step-Guide-to-Build-a-Fact-Skill
