### ISSUE TITLE
invalid manifest

### ISSUE THREAD

**Issue by nealrs** [alexa/skill-sample-nodejs-hello-world#14]
I tried cloning & deploying this repo per instructions and received an `Invalid skill manifest` error.
![screen shot 2018-06-14 at 11 19 26 am](https://user-images.githubusercontent.com/1568188/41421466-e63a758c-6fc4-11e8-8dd2-27edbdcdb6c0.png)

**Comment by franklin-lobb** [comment]
Hi @nealrs - I tried using the same steps and could not reproduce this.  I've seen this sometimes happen when you use an profile other than 'default' and usually traces back to a configuration or other error.  A few things you might try:
1. recreate the configuration using `ask init`
2. recreate the default profile to be the one you want to use
3.  verify you have the latest version of the CLI (`ask --version`, update it: `npm install -g ask-cli`)
