### ISSUE TITLE
Not working with new Developer Portal

### ISSUE THREAD

**Issue by RaphaelHerd** [alexa/skill-sample-nodejs-hello-world#16]
All tutorials are not working with the new developer portal. I'm new to Alexa but very common to AWS in general and it's very frustrating that AWS is changing the UI and the semantics of the templates without modifying the HowTos.

**Comment by elewin** [comment]
Same, I'm trying to work through this and I'm completely stuck on the Lambda Function part; none of the tutorial matches what I'm seeing, and I can't find what they want me to do

**Comment by franklin-lobb** [comment]
Thanks for the feedback.  The tutorials are updated to include the Alexa Hosted option and should be working.
