### ISSUE TITLE
Issue with formatting in instructions

### ISSUE THREAD

**Issue by sentrychris** [alexa/skill-sample-nodejs-hello-world#26]
Hi,

I noticed an issue with the formatting for [this file](https://github.com/alexa/skill-sample-nodejs-hello-world/blob/master/instructions/4-testing.md):

![image](https://user-images.githubusercontent.com/42321445/49004489-444d4500-f15c-11e8-9f48-00b4b082e107.png)

**Comment by franklin-lobb** [comment]
Thanks for submitting.  PR resolved.
