### ISSUE TITLE
The save option for npm install is no longer necessary

### ISSUE THREAD

**Issue by sabuncu** [alexa/skill-sample-nodejs-hello-world#29]
In file [7-cli.md](https://github.com/alexa/skill-sample-nodejs-hello-world/blob/master/instructions/7-cli.md), item 4 under Installation, the instructions for **npm install** specify the **--save** option which is no longer required (as of npm 5.0.0).  In fact, the bash command line shown below the text does not specify that option.  The text needs to be fixed. 

Supporting evidence: [This answer](https://stackoverflow.com/a/19578808/360840) on SO.

**Comment by franklin-lobb** [comment]
good catch.  the ASK CLI will also run `npm install` prior to deploying, so this step is entirely optional now.  I've removed the `--save` and will make further updates in the next revision.

**Comment by sabuncu** [comment]
Thank you!  Can't tell you how good it feels for a contribution (albeit a small one) to be recognized.  (And on a Saturday to boot!)  Regards.

PS: I have translated most of this repo into [Turkish](https://github.com/sabuncu/skill-sample-nodejs-hello-world), including the graphics.  The 7-cli.md file is the only one left. :)
