### ISSUE TITLE
To run ask init, navigating into the repo folder is not required.

### ISSUE THREAD

**Issue by sabuncu** [alexa/skill-sample-nodejs-hello-world#30]
In file [7-cli.md](https://github.com/alexa/skill-sample-nodejs-hello-world/blob/master/instructions/7-cli.md), item 3 under Installation, the instructions for running _ask init_ mention the need to first navigate into the repo folder.  This is not necessary, as _ask init_ is a command that needs to be performed one-time only (after installation of the ASK CLI), and not per each repository.  Item 3 should simply mention the need to run _ask init_ if it hasn't been run before.

Supporting evidence: [ASK CLI init command documentation](https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html?#init-command).

**Comment by franklin-lobb** [comment]
We agree.  Those changes have been incorporated into the latest instructions
