### ISSUE TITLE
Using this without Lambda

### ISSUE THREAD

**Issue by umaar** [alexa/skill-sample-nodejs-hello-world#4]
All the examples I've encountered seem to be tightly coupled to using Lambda.

It'd be very useful to enhance these examples so they can be run standalone, on someones personal web server for example (still using a Node.js environment). Thanks!

**Comment by kleinfreund** [comment]
I’m interested in this as well as I’m unable to register for an AWS account (no credit/debit card).

Can someone point me to a simple sample like the ones shown in the *skill-sample-nodejs-…* repositories and how to use them without AWS Lambda? Is that even possible?

**Comment by alninyo** [comment]
Hi, yes for me is it interested too. i search somebody that help me together to build Alexa Skills.
Greetings Sandro

**Comment by Dallanosm** [comment]
Hi, could be this possible? Thanks.

Best regards,
Daniel.

**Comment by franklin-lobb** [comment]
Here are the details for what is required if you want to use something other than AWS Lambda: https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html  I've made a note that a sample/walkthrough is something that you'd like.
