### ISSUE TITLE
Add AMAZON.FallbackIntent and handler to ask-cli-x branch

### ISSUE THREAD

**Issue by habuma** [alexa/skill-sample-nodejs-hello-world#47]
A lot of what has been added in the `master` branch in the past year or so is, IMO, unnecessary. But, I did enjoy seeing the addition of the `AMAZON.FallbackIntent` and would like to see it in the `ask-cli-x` branch for users of the new ASK CLI v2.0.x.

Without this intent and a corresponding handler, almost any utterance will match the `HelloWorldIntent`, even if the match is very low...making the list of sample utterances for `HelloWorldIntent` seem pointless. With the fallback intent in play, the utterances that match `HelloWorldIntent` make more sense and other utterances that don't make sense get captured by the fallback intent.

Moreover, the fallback intent is something that most Alexa skills will want to have in play, so including it in this template eliminates the need for the skill developer to add it themselves.

**Comment by aszk** [comment]
@habuma Thank you for your feedback. We added FallbackIntent.
