### ISSUE TITLE
Skill Sample AWS-Hosted Solution Link Broken

### ISSUE THREAD

**Issue by harrysolovay** [alexa/skill-sample-nodejs-hello-world#69]
In the ["three options for skill setup"](https://github.com/alexa/skill-sample-nodejs-hello-world#three-options-for-skill-setup) section, the third bullet point's link `AWS-Hosted instructions` link is a 404.

**Comment by aszk** [comment]
We confirmed the issue. A file that is linked from [AWS-Hosted instructions](https://github.com/alexa-samples/skill-sample-nodejs-hello-world/blob/master/instructions/setup-vui-aws-hosted.md) on https://github.com/alexa-samples/skill-sample-nodejs-hello-world page doens't exist. I will work on this and let you know once I find the solution.

**Comment by aszk** [comment]
We temporarily retrieved files for AWS Hosted instructions.
