### ISSUE TITLE
Update ask-sdk-core version

### ISSUE THREAD

**Issue by habuma** [alexa/skill-sample-nodejs-hello-world#73]
package.json specifies ask-sdk-core to be "^2.6.0". But that means that any skill initialized with `ask new` and selecting AWS Lambda hosting will not be able to take advantage of newer features such as APL-A in the response.

Recommend updating ask-sdk-core to "^2.11.0" (or higher). Might also have a look at the other versions in package.json as well to be sure that they're up-to-date.

**Comment by aszk** [comment]
@habuma Thank you for waiting our update. We have updated the branch.
