### ISSUE TITLE
Hello World Example - AWS hosted instructions

### ISSUE THREAD

**Issue by gnanisekar** [alexa/skill-sample-nodejs-hello-world#75]
The link for AWS hosted instructions in the Hello World Example link is having issue - The 'alexa-samples/skill-sample-nodejs-hello-world' repository doesn't contain the 'instructions/setup-vui-aws-hosted.md' path in 'master'.

**Comment by aszk** [comment]
I can see https://github.com/alexa-samples/skill-sample-nodejs-hello-world/blob/master/instructions/setup-vui-alexa-hosted.md. Could you give me more details on this issue?

**Comment by aszk** [comment]
We confirmed the issue. A file that is linked from [AWS-Hosted instructions](https://github.com/alexa-samples/skill-sample-nodejs-hello-world/blob/master/instructions/setup-vui-aws-hosted.md) on https://github.com/alexa-samples/skill-sample-nodejs-hello-world page doens't exist. I will work on this and let you know once I find the solution.

**Comment by aszk** [comment]
Duplicated of https://github.com/alexa-samples/skill-sample-nodejs-hello-world/issues/69
